# AI-Thinker ESP32-CAM specific configuration
device:
  id: "ai_thinker_001"
  board_type: "ai_thinker"
  camera_model: "ov2640"

# Pin configuration for AI-Thinker ESP32-CAM
pins:
  PWDN: 32
  RESET: -1
  XCLK: 0
  SIOD: 26
  SIOC: 27
  Y9: 35
  Y8: 34
  Y7: 39
  Y6: 36
  Y5: 21
  Y4: 19
  Y3: 18
  Y2: 5
  VSYNC: 25
  HREF: 23
  PCLK: 22
  LED_FLASH: 4

camera:
  resolution: "1024x768"  # XGA
  frame_format: "jpeg"
  jpeg_quality: 12
  brightness: 0
  contrast: 0
  saturation: 0
  vertical_flip: false
  horizontal_mirror: false
  frame_rate: 15

power:
  voltage: "5V"
  current: "800mA"
  enable_power_saving: true

features:
  - wifi
  - camera
  - microsd
  - gpio
  - flash_led
