AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets Manager secret for accelerapp/db/credentials
Resources:
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: accelerapp/db/credentials
      Description: Database credentials for Accelerapp
      Tags:
      - Key: Purpose
        Value: Database
      - Key: Environment
        Value: production
      - Key: ManagedBy
        Value: accelerapp
  RotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      SecretId:
        Ref: Secret
      RotationLambdaARN:
        Ref: RotationLambdaArn
      RotationRules:
        AutomaticallyAfterDays: 30
Outputs:
  SecretArn:
    Description: ARN of the secret
    Value:
      Ref: Secret
    Export:
      Name: accelerapp/db/credentials-arn
  SecretName:
    Description: Name of the secret
    Value: accelerapp/db/credentials
Parameters:
  RotationLambdaArn:
    Type: String
    Description: ARN of the rotation Lambda function
