"""
Tests for the OBC hardware registry consumer (Ecosystem Integration I1).

The bundled registry.json is generated by Oh-Ben-Claw's `emit-registry` binary
from the canonical Rust catalog — these tests pin that Accelerapp reads it
correctly and routes registry boards onto the right code-generation platforms.
"""

import json

import pytest

from accelerapp.hardware.registry import (
    SUPPORTED_SCHEMA_VERSION,
    Registry,
    RegistrySchemaError,
    boards_for_platform,
    default_registry,
    load_registry,
    platform_for_board,
)
from accelerapp.platforms import get_platform


class TestLoadRegistry:
    def test_bundled_registry_loads(self):
        reg = load_registry()
        assert reg.schema_version == SUPPORTED_SCHEMA_VERSION
        assert len(reg.boards) > 40
        assert len(reg.accessories) > 10

    def test_default_registry_is_cached(self):
        assert default_registry() is default_registry()

    def test_env_var_override(self, tmp_path, monkeypatch):
        doc = {"schema_version": 1, "boards": [], "accessories": []}
        p = tmp_path / "registry.json"
        p.write_text(json.dumps(doc), encoding="utf-8")
        monkeypatch.setenv("OBC_REGISTRY_PATH", str(p))
        reg = load_registry()
        assert reg.boards == []

    def test_unsupported_schema_version_raises(self, tmp_path):
        doc = {"schema_version": 999, "boards": [], "accessories": []}
        p = tmp_path / "registry.json"
        p.write_text(json.dumps(doc), encoding="utf-8")
        with pytest.raises(RegistrySchemaError):
            load_registry(p)

    def test_missing_file_raises(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            load_registry(tmp_path / "nope.json")


class TestLookups:
    @pytest.fixture(scope="class")
    def reg(self) -> Registry:
        return load_registry()

    def test_find_board_by_name(self, reg):
        esp32 = reg.find_board("esp32-s3")
        assert esp32 is not None
        assert esp32.has_capability("gpio")

    def test_find_by_usb(self, reg):
        # Every board resolves back through its own USB ids.
        b = reg.boards[0]
        assert reg.find_by_usb(b.vid, b.pid) is not None
        assert reg.find_by_usb(0xFFFF, 0xFFFF) is None

    def test_boards_with_capability(self, reg):
        cams = reg.boards_with_capability("camera_capture")
        assert len(cams) >= 1
        assert all(b.has_capability("camera_capture") for b in cams)

    def test_accessories_present(self, reg):
        bme = reg.find_accessory("bme280")
        assert bme is not None
        assert bme.bus == "i2c"
        assert bme.default_i2c_addr is not None

    def test_board_names_distinct(self, reg):
        names = reg.board_names()
        assert len(names) == len(set(names))
        assert "esp32-s3" in names

    def test_registry_carries_vendor_and_connectors(self, reg):
        for b in reg.boards:
            assert isinstance(b.vendor, str)
            assert isinstance(b.connectors, list)


class TestPlatformRouting:
    @pytest.fixture(scope="class")
    def reg(self) -> Registry:
        return load_registry()

    def test_esp32_routes_to_esp32(self, reg):
        b = reg.find_board("esp32-s3")
        assert platform_for_board(b) == "esp32"

    def test_nucleo_routes_to_stm32_family(self, reg):
        b = reg.find_board("nucleo-f401re")
        assert platform_for_board(b) in ("stm32", "stm32f4")

    def test_every_routed_platform_is_instantiable(self, reg):
        """Any platform name we emit must be accepted by get_platform()."""
        routed = {platform_for_board(b) for b in reg.boards} - {None}
        assert routed, "expected at least one routable board"
        for name in routed:
            assert get_platform(name) is not None

    def test_usb_bridges_are_not_routed(self, reg):
        bridge = reg.find_board("cp2102")
        if bridge is not None:
            assert platform_for_board(bridge) is None

    def test_boards_for_platform_consistent(self, reg):
        esp_boards = boards_for_platform("esp32", reg)
        assert len(esp_boards) >= 1
        assert all(platform_for_board(b) == "esp32" for b in esp_boards)
