# Performance Optimization Configuration for Accelerapp

performance:
  # Caching configuration
  caching:
    enabled: true
    
    # Cache backend: memory, redis
    backend: memory
    
    # Default TTL in seconds
    default_ttl: 3600
    
    # Maximum cache size (entries)
    max_size: 1000
    
    # Cache invalidation strategy
    invalidation: lru  # lru, lfu, ttl
    
    # Redis configuration (if backend is redis)
    redis:
      host: localhost
      port: 6379
      db: 0
      password: null
  
  # Async processing
  async:
    enabled: true
    
    # Maximum concurrent operations
    max_concurrency: 10
    
    # Worker pool size
    worker_pool_size: 4
    
    # Task timeout (seconds)
    task_timeout: 300
  
  # Resource pooling
  pools:
    # Database connection pool
    database:
      min_size: 2
      max_size: 10
      timeout: 30
    
    # HTTP connection pool
    http:
      max_connections: 100
      max_keepalive: 50
      timeout: 30
  
  # Memory optimization
  memory:
    # Enable garbage collection tuning
    gc_tuning: true
    
    # Memory limit (MB, 0 = no limit)
    limit_mb: 0
    
    # Enable memory profiling
    profiling: false
  
  # Background processing
  background:
    enabled: true
    
    # Queue backend: memory, redis
    queue_backend: memory
    
    # Maximum queue size
    max_queue_size: 1000
    
    # Number of worker threads
    workers: 2
