"""
OBC shared firmware templates — Ecosystem Integration I6.

The canonical starter-sketch template set is generated by Oh-Ben-Claw's
``emit-firmware-templates`` binary (one capability-conditioned Arduino sketch
per flashable registry board) and bundled here as ``templates.json`` —
refreshed alongside ``registry.json``::

    # in Oh-Ben-Claw
    cargo run --bin emit-firmware-templates -- firmware-templates/templates.json
    cp firmware-templates/templates.json ../Accelerapp/src/accelerapp/firmware/templates.json

Use :func:`template_for_board` for the OBC node-protocol scaffold, and
:func:`codegen_route` to decide how Accelerapp should treat a registry board:
start from the shared scaffold, route to one of Accelerapp's platform
generators, or both.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import List, Optional, Tuple

from accelerapp.hardware.registry import Board, platform_for_board

#: The templates.json schema this consumer understands (mirrors OBC's
#: TEMPLATES_SCHEMA_VERSION).
SUPPORTED_TEMPLATES_SCHEMA_VERSION = 1

#: Environment variable overriding the bundled template document.
TEMPLATES_PATH_ENV = "OBC_FIRMWARE_TEMPLATES_PATH"

_BUNDLED = Path(__file__).parent / "templates.json"

#: The node id baked into canonical templates, to be substituted per node.
NODE_ID_PLACEHOLDER = "obc-node"


class TemplatesSchemaError(RuntimeError):
    """The template document's schema_version is unsupported."""


@dataclass(frozen=True)
class FirmwareTemplate:
    """One canonical starter sketch for a flashable registry board."""

    board: str
    language: str
    filename: str
    source: str
    capabilities: List[str]
    vendor: str

    def with_node_id(self, node_id: str) -> "FirmwareTemplate":
        """The same template with the placeholder node id substituted."""
        return FirmwareTemplate(
            board=self.board,
            language=self.language,
            filename=self.filename,
            source=self.source.replace(NODE_ID_PLACEHOLDER, node_id),
            capabilities=self.capabilities,
            vendor=self.vendor,
        )


def load_templates(path: Optional[os.PathLike] = None) -> List[FirmwareTemplate]:
    """Load and validate the template document (path → env var → bundled)."""
    resolved = Path(path) if path else Path(os.environ.get(TEMPLATES_PATH_ENV, _BUNDLED))
    with open(resolved, encoding="utf-8") as f:
        doc = json.load(f)

    version = doc.get("schema_version")
    if version != SUPPORTED_TEMPLATES_SCHEMA_VERSION:
        raise TemplatesSchemaError(
            f"templates.json schema_version {version!r} is not supported "
            f"(this consumer understands {SUPPORTED_TEMPLATES_SCHEMA_VERSION})"
        )

    return [
        FirmwareTemplate(
            board=t["board"],
            language=t.get("language", "arduino"),
            filename=t["filename"],
            source=t["source"],
            capabilities=list(t.get("capabilities", [])),
            vendor=t.get("vendor", ""),
        )
        for t in doc.get("templates", [])
    ]


@lru_cache(maxsize=1)
def _bundled() -> List[FirmwareTemplate]:
    return load_templates()


def template_for_board(board_name: str, node_id: Optional[str] = None) -> Optional[FirmwareTemplate]:
    """The shared OBC starter sketch for a board, optionally node-id'd."""
    t = next((t for t in _bundled() if t.board == board_name), None)
    if t is None:
        return None
    return t.with_node_id(node_id) if node_id else t


def codegen_route(board: Board) -> Tuple[Optional[str], Optional[FirmwareTemplate]]:
    """
    How should Accelerapp generate firmware for this registry board?

    Returns ``(platform_name, template)``:
    - ``platform_name`` — an Accelerapp platform generator (``get_platform``)
      when the board maps to one, else ``None``;
    - ``template`` — the shared OBC node-protocol scaffold when the board is
      flashable, else ``None``.

    Typical use: start from the scaffold (correct OBC announce/command
    skeleton), then generate platform-specific drivers with the platform
    generator.
    """
    return platform_for_board(board), template_for_board(board.name)
