---
# Jaeger All-in-One Deployment (for development/testing)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-all-in-one
  namespace: observability
  labels:
    app: jaeger
    component: all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
      component: all-in-one
  template:
    metadata:
      labels:
        app: jaeger
        component: all-in-one
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.50
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          ports:
            - containerPort: 5775
              protocol: UDP
              name: zipkin-compact
            - containerPort: 6831
              protocol: UDP
              name: jaeger-compact
            - containerPort: 6832
              protocol: UDP
              name: jaeger-binary
            - containerPort: 5778
              name: config
            - containerPort: 16686
              name: query
            - containerPort: 14250
              name: grpc
            - containerPort: 14268
              name: collector
            - containerPort: 14269
              name: admin
            - containerPort: 9411
              name: zipkin
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: observability
  labels:
    app: jaeger
    component: collector
spec:
  type: ClusterIP
  ports:
    - port: 14250
      targetPort: 14250
      name: grpc
    - port: 14268
      targetPort: 14268
      name: http
    - port: 9411
      targetPort: 9411
      name: zipkin
    - port: 4317
      targetPort: 4317
      name: otlp-grpc
    - port: 4318
      targetPort: 4318
      name: otlp-http
  selector:
    app: jaeger
    component: all-in-one
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: observability
  labels:
    app: jaeger
    component: query
spec:
  type: ClusterIP
  ports:
    - port: 16686
      targetPort: 16686
      name: query
  selector:
    app: jaeger
    component: all-in-one
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: observability
  labels:
    app: jaeger
    component: agent
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5775
      targetPort: 5775
      protocol: UDP
      name: zipkin-compact
    - port: 6831
      targetPort: 6831
      protocol: UDP
      name: jaeger-compact
    - port: 6832
      targetPort: 6832
      protocol: UDP
      name: jaeger-binary
    - port: 5778
      targetPort: 5778
      name: config
  selector:
    app: jaeger
    component: all-in-one
